### ISSUE TITLE
No other tools than trace viewer

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/profiler#1]
I wanted to use the profiler to have a better UI to inspect my model performance than the trace viewer currently in tensorboard.

However, when using the profiler, I don't have anything other than the trace viewer (and the other tensorboard tabs):
![profiler_trace_viewer](https://user-images.githubusercontent.com/6387497/78054211-fd8be280-7381-11ea-95f4-44d3a69157d4.png)

This is the logs I get when running `install_profiling.py`:
```
Running virtualenv with interpreter /usr/bin/python3
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /volatile/home/Zaccharie/workspace/profiler/profile_env/bin/python3
Not overwriting existing python script /volatile/home/Zaccharie/workspace/profiler/profile_env/bin/python (you must use /volatile/home/Zaccharie/workspace/profiler/profile_env/bin/python3)
Installing setuptools, pip, wheel...
done.
WARNING: Skipping tensorboard as it is not installed.
WARNING: Skipping tensorflow as it is not installed.
2020-03-31 19:14:33.325188: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
TensorBoard 2.3.0a20200331 at http://is240490:6007/ (Press CTRL+C to quit)
```

The exact command I run is the following: `python3 install_and_run.py --envdir=profile_env --logdir=../path/to/my/logs`.

My versions are (tf and tb used to generate the logs):
- Tf : 2.1.0
- Tb: 2.2.0
- CUDA: 10.1
(if you need others tell me)

**Comment by zaccharieramzi** [comment]
As a side note, I notice that my logs do not ressemble the ones I found in the demo folder. Basically the profile part consists of one `local.trace` file as opposed to a wide variety of files in the demo folder.

**Comment by zaccharieramzi** [comment]
As another side note, I used the fix suggested [here](https://github.com/tensorflow/tensorboard/issues/3209) to deal with the chrome 80+ / tensorboard bug, that is I started google chrome using `google-chrome --enable-blink-features=ShadowDOMV0,CustomElementsV0,HTMLImports`

**Comment by qiuminxu** [comment]
Hi @zaccharieramzi, the new tools are only available starting TF 2.2.  Can you update your tensorflow to 2.2.0rc2 and try again? https://pypi.org/project/tensorflow/2.2.0rc2/

**Comment by zaccharieramzi** [comment]
oh ok so the creation of the logs needs to happen with tf 2.2. Ok it all makes sense.
And is there by any chance a script or something similar that could transform my `local.trace` file in the right format? I will run with tf 2.2, but on some remote computers I am using I cannot choose the tensorflow version that easily (and those computers have different GPUs than I do so the results will surely be different).

**Comment by qiuminxu** [comment]
There isn't a converter from local.trace to other tools yet, we rely on more detailed intermediate format that isn't included in local.trace.

**Comment by zaccharieramzi** [comment]
Too bad, do you know if implementing a converter is in the pipeline?

**Comment by zaccharieramzi** [comment]
Everything works fine with tf 2.2, it looks really good, I would be so thrilled to have a converter for tf 2.1!!
