### ISSUE TITLE
[라이브 TV!]*팔레스타인 vs 한국 라이브 방송 무료 2024년 11월 19일

### ISSUE THREAD

**Issue by tipen123** [tensorflow/profiler#1073]
[현장 LIVE] ‘손흥민-이강인 동시 출격’ 홍명보호, 팔레스타인전 대승 노린다
대한민국
World Cup Qualification AFC
팔레스타인 vs 대한민국
팔레스타인
[골닷컴, 암만 요르단] 김형중 기자 = 4연승 행진을 달리고 있는 축구 국가대표팀이 팔레스타인전 대승을 노린다. 에이스 손흥민과 이강인은 동시 선발 출격한다.

홍명보 감독이 이끄는 대표팀은 19일 오후 11시(한국시각) 요르단 수도 암만에 위치한 암만 인터내셔널 스타디움에서 2026 국제축구연맹(FIFA) 북중미 월드컵 아시아지역 3차 예선 B조 6차전 팔레스타인과 원정 경기를 치른다.

현재 승점 13점으로 조 1위를 달리고 있는 한국은 이날 승리할 경우 북중미 월드컵 본선 진출의 8부 능선을 넘게 된다. 또한 지난 9월 홈에서 열린 1차전에서 0-0 무승부를 거둔 팔레스타인을 상대로 설욕에 나서겠다는 각오다.

홍명보 감독은 선발 명단에 변화를 주지 않았다. 지난 14일 승리를 거둔 쿠웨이트전과 동일한 선발 라인업으로 나선다.

최전방에는 오세훈이 선다. 양 측면에는 손흥민과 이강인이 포진한다. 2선 중앙에는 이재성이 서고, 그 뒤에서 황인범과 박용우가 자리한다. 김민재와 조유민의 센터백 조합과 양 풀백 이명재와 설영우가 포백을 구성한다. 골문은 조현우가 지킨다.

벤치에는 김경민, 김문환, 백승호, 주민규, 오현규, 이창근, 이태석, 정승현, 이기혁, 홍현석, 배준호, 권경원이 출격을 기다린다. 김봉수, 이현주, 정우영은 명단에서 제외되었다.

캡틴 손흥민은 자신의 A매치 통산 51골에 도전한다. 현재 50골로 황선홍 대전하나시티즌 감독과 함께 역대 한국 선수 최다득점 공동 2위에 올라있다. 이날 득점에 성공한다면 단독 2위에 오르는 동시에, 2024년 A매치 두 자릿수 득점 고지에 오르게 된다.

신흥 에이스 이강인은 홍명보호 첫 골을 노린다. 지난 6월 중국과의 2차 예선 마지막 경기에서 결승골을 터트렸던 이강인은 3차 예선 5경기에서 아직 득점이 없다. 쿠웨이트전에서도 90분을 소화하며 좋은 컨디션을 보여줬기 때문에 골 소식이 기대된다

**Comment by vuterbox** [comment]
ccccccccc


[![wer](https://github.com/user-attachments/assets/3025ba76-8ee1-4fe9-9119-6f60093e082b)](https://bit.ly/3Z0z1cz)



[![wer](https://github.com/user-attachments/assets/ba76c8db-fa4a-437e-8405-af0335443109)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/199ab3a9-0845-41ab-9231-1912a342d29b)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/329599bf-77a4-411b-b577-cdb3c94986d8)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/90096759-ff09-4c3b-9e49-6f4397652bbc)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/482dc188-8847-4bd3-9501-139d9f62ca46)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/b5bdb8f4-f3e9-4c9d-ac6e-a10a1da352e2)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/0b7ea2a3-83ca-4ff6-8c7f-e716ff6e7ff9)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/b4472ec9-5d7c-4dc0-b64e-c6191fa0ca4d)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/5bc2de97-151d-46a0-914e-b4c70e8b9a39)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/a0c47e7c-d44d-4a0b-8c83-9d0622f4dc91)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/d28ae9c2-62c5-4486-a839-6448c139d66f)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/33ebab5b-a38c-4fd2-91d5-033c1967965f)](https://bit.ly/3Z0z1cz)


vvvvvvvvvvv
