### ISSUE TITLE
Idle Time 

### ISSUE THREAD

**Issue by piepor** [tensorflow/profiler#120]
Hi everyone,
I started using the Tensorflow profiler, which i found very useful, with the tutorial ([https://github.com/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb](url)) and with a custom model.
In both cases, the idle time in Tensorflow stats is about 90%: is this normal? Why the option "Include idle time" is not the default one?

**Comment by ckluk-github** [comment]
Is the idle time in TensorFlow Stats on host? or on device?
If it is on host, it is probably okay. It means that your model doesn't use the host much.
If it is on device, it means that your accelerator is largely not used. You probably want to increase its utilization.
"Include idle time" is not the default because many users of TensorFlow Stats want to visualize the relative timing of actual ops. If we include the idle time, the actual-op portions may become too small to visualize clearly.

**Comment by piepor** [comment]
Thanks for the quick response,
It was on both sides: the device and the host. Unfortunatly I can't provide logs in these days but i will as soon as possible, hoping that you could suggest me how to increase gpu utilization. 
I have another question: is there a guide, conference, course or something else where i can learn to interprete the logs and the trace view of the profiler? This way i can try to solve my code optimization asking here as little as possible.

**Comment by ckluk** [comment]
We are working on the guide, hopefully to be available soon.
Thanks
-ck

**Comment by ckluk-github** [comment]
As for the guide, you can look at the current one (https://www.tensorflow.org/guide/profiler#profiler_tools). We are working on a more detailed one with examples.

For your issue, what is the step-time breakdown shown on the Overview Page?

**Comment by piepor** [comment]
> We are working on the guide, hopefully to be available soon.
Thanks
-ck

Ok great!

My step-time breakdown is
![step-time](https://user-images.githubusercontent.com/55095421/90421461-b9dc1000-e0b9-11ea-8a9e-eca94c7cf0b1.png)
This is my full profile log [profile_logs.zip](https://github.com/tensorflow/profiler/files/5085620/profile_logs.zip).
I think that the problem is that my model is really little, so most of the time is spent on kernel launch. This is supported also by the fact that using only CPU the training speeds up. 
Is there a way to effectively use the GPU? Or for this model I have to give up using only the CPU? 
Thank you very much

**Comment by piepor** [comment]
> We are working on the guide, hopefully to be available soon.
Thanks
-ck

Ok great!

![step-time](https://user-images.githubusercontent.com/55095421/90423001-0294c880-e0bc-11ea-9634-c7815389e5e4.png)

This is my full profile log [profile_logs.zip](https://github.com/tensorflow/profiler/files/5085726/profile_logs.zip)
I think that the problem is that my model is a really little one, so most of the time is spent in launching kernels. This is also supported by the fact that using only the CPU speeds up the training. Is there a way to effectively use the GPU? Or for this model I have to give up using only the CPU?
Thank you very much

**Comment by ydennisy** [comment]
@ckluk any more advice here? I am facing the same issue - the profiler tool is great, but it is very hard to optimise the kernel launch time, any more advice or guides in this area?

**Comment by siwang2011** [comment]
@ckluk-github 
hello, i use cpu train the model, the idle time is 97.5% is it normal?
thanks

**Comment by nithish08** [comment]
@ckluk-github , I am repeating question from @siwang2011 , 
If we are using CPU for training, is idle time ~90% normal?
