### ISSUE TITLE
How to profile multi-worker GPU?

### ISSUE THREAD

**Issue by pingsutw** [tensorflow/profiler#13]
I want to profile my distributed training,  I see README description
`To profile multi-worker GPU configurations, profile individual workers independently.`
But I still can not understand what is mean.
what if I set log dir to `hdfs` or `S3`, could I get multi worker profile data?
could I get network utilization between two nodes?
are there any examples of distributed training? 
`

**Comment by qiuminxu** [comment]
Hi, @pingsutw, thanks for your question. Multi-worker GPU profiling is not supported yet, and we're working on it.
You maybe able to hack through and profile individual workers. For example, run profiler.start and profiler.stop inside the distribution strategy, and go to individual workers to fetch the profile data back. In this way, you will be profiling as if profiling single GPU worker.  Let me know if this works for you.

**Comment by pingsutw** [comment]
@qiuminxu Thanks for the reply, is there any roadmap about Multi-worker GPU.
I'm very interested in this issue, and also want to contribute and work on these issues.
Who should I contact? my email - `pingsutw@apache.com`

**Comment by qiuminxu** [comment]
@pingsutw Are you interested in multi-worker GPU profiling or multi worker training on GPUs?
Here is a TF discuss forum where you can ask and participate in questions about TF multi worker support. https://groups.google.com/a/tensorflow.org/g/discuss

We're targeting to support multi-worker GPU profiling in the coming releases (TF 2.3 or 2.4). If you're interested in specific tools/FRs for multi GPU performance analysis, you can file an issue here. You are also welcome to participate in adding features once the most basic support is available. Thanks very much for your interest to contribute!

**Comment by pingsutw** [comment]
@qiuminxu The link seems not working
I'm interested in multi-worker GPU profiling and model performance analysis tools like this repo.
If any developed feature that I could help, please let me know. I'm very happy to contribute.

**Comment by qiuminxu** [comment]
Thanks. How about the discuss link in this page? https://www.tensorflow.org/community/forums

**Comment by pingsutw** [comment]
Greats, Thanks @qiuminxu.

**Comment by qiuminxu** [comment]
Profiling multi-worker GPU is now supported in TF 2.4.

**Comment by delucca** [comment]
> Profiling multi-worker GPU is now supported in TF 2.4.

Thanks for reporting that. Is there an example on how to profile multi-worker?
