### ISSUE TITLE
Profiler tap on Tensorflow is blank

### ISSUE THREAD

**Issue by ingolfured** [tensorflow/profiler#133]
Hello

I'm running 

Tensorflow 2.3.0 
Tensorboard 2.3.0

After successfully profiling a job, I start up Tensorboard on the same server as I trained using
```
tensorboard --bind_all --logdir=`pwd`
```

Later, I open up my Chrome (or Firefox), select the profile tap and get a blank screen. The chrome console shows an error
```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED  - www.gstatic.com/charts/loader.js
```
I believe it's [this line](https://github.com/tensorflow/profiler/blob/26cf2bd57346c1944425a8b686112841d609e04c/frontend/index.html#L27)

The workstation is not connected to the internet. Is there any possibility to run the profiling tool locally without needing the world wide web?

Thanks

**Comment by ckluk** [comment]
The Profiler uses Google Charts, which currently requires internet access.
There is no way to work around it. Thanks.

**Comment by HaneulKim214** [comment]
In the documentation https://www.tensorflow.org/guide/profiler it says 

> Note: The Profiler requires internet access to load the [Google Chart libraries](https://developers.google.com/chart/interactive/docs/basic_load_libs#basic-library-loading). Some charts and tables may be missing if you run TensorBoard entirely offline on your local machine, behind a corporate firewall, or in a data center.

Only some charts may be missing, I'm having the same problem where profile tab shows blank page. Is it expected behavior? As I expected at least some rudimentary graphs.
