### ISSUE TITLE
How to output the data from tensorboard?

### ISSUE THREAD

**Issue by Young768** [tensorflow/profiler#17]
Hi, TF experts

I want to profile and analyze the execution time for each iteration using tensorboard. Can I read the data from tensorboard? For example, I want to save the step-time information to a CSV file.

**Comment by ckluk** [comment]
Hi,

Can you provide the following information:
(1) Are you using Keras? or Estimator?
(2) Which TF version are you using?

Thanks,
-ck

**Comment by Young768** [comment]
Keras on TF-nightly

**Comment by ckluk** [comment]
I don't think that TensorBoard gives you the step time.

I can see a couple of options:
(1) If what you need is simply step time, you can add a Keras custom
callback (https://www.tensorflow.org/guide/keras/custom_callback) to print
the timestamp at each step to a file. Then you can write a script to
convert the step times to CSV from this file.
(2) You can also use the new TF2 profile (
https://www.tensorflow.org/guide/profiler). It has a step-time graph.
However, it currently doesn't have an option to output the statistics to a
file. So, it won't be easy for you to generate a CSV file automatically
(although it is possible by writing a script to parse the JSON file which
contains the profiling data).

**Comment by Young768** [comment]
@ckluk Yep, what I mean is the profiler. I thought that profiler is the part of tensorboard. Sorry for the confusion. I will try these two options.

**Comment by Young768** [comment]
I have one more question. For option one, what if I use Estimator? is there any callback like keras?

**Comment by ckluk** [comment]
I think you can use the SessionRunHook in Estimator, such as this one:
https://www.tensorflow.org/api_docs/python/tf/estimator/StepCounterHook

**Comment by Young768** [comment]
Thanks @ckluk
