### ISSUE TITLE
View Peak Memory Usage in MB

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/profiler#174]
Is it possible to view the peak memory usage in mb instead of gb? In my use case, gb is too coarse. Thanks in advance.

![image](https://user-images.githubusercontent.com/12474257/94784940-e5cb0080-039c-11eb-94c1-fd57f7097a21.png)

**Comment by qiuminxu** [comment]
The tool will be able to show the peak heap usage in MB in the next nightly release.
