### ISSUE TITLE
Troubling overview

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/profiler#2]
My model is taking especially long to run, so I wanted to investigate using profiler.

I am having this weird overview:
![troublin_overview](https://user-images.githubusercontent.com/6387497/78114232-3b7c1b80-7401-11ea-9fca-e6e522cde8cb.png)

What bugs me is that my program is said to be not I/O bound but I see that only 5% of the time is spent on device (kernel launch + device compute time). 
It's like if this "All Others Time" is not counted as I/O, even though it takes all of the total time.

Even weired, when I look at the tensorflow stats, 96% of device time is IDLE.

My guess is that my program is a bit difficult to parse because I am using a `tf.py_function` at some point. This function reads HDF5 data, which at the moment I can't read using tfio because it's [failing in multi-threaded mode](https://github.com/tensorflow/io/issues/745).
I think it should still be counted as I/O.

**Comment by zaccharieramzi** [comment]
As it turned out there was indeed some improvement that could be made in my I/O. I was loading the full HDF5 datasets when I only needed parts of it. I think the comment about I/O should be qualified when there is a lot of `py_function` time.

**Comment by ckluk** [comment]
Hi Zaccharie,

Thanks for using the Profiler and your feedback.
Our Profiler recognizes an operation as I/O if they are known input or
output operations (e.g, the
https://www.tensorflow.org/api_docs/python/tf/data/Dataset)
Other operations like the Python activities would be classified as "All
Others".
I think we can improve the message and documentation as you suggested.

-ck

**Comment by zaccharieramzi** [comment]
Well my `py_function` is used in the `map` of a `tf.data.Dataset` so it is part of a classical tf input data pipeline.

**Comment by ckluk** [comment]
We look for some specific patterns in the trace of tf.data to decide if it
is I/O bounded. Perhaps, our heuristics is missing something.
It would be great if you can upload your entire profile log directory so
that we can look at your traces in details.

Thanks,
-ck

**Comment by zaccharieramzi** [comment]
Here you go:
[logs.zip](https://github.com/tensorflow/profiler/files/4416789/logs.zip)

**Comment by ckluk** [comment]
Thanks for the log. After looking at the detailed trace, I agree that it could be I/O related overhead. Nevertheless, it is challenging for our automatic analysis to figure this out right now. So, I think the best that we can do now is to add more information on what "All Others Time" means, such as:
   "73.4% of the total step time sampled is spent on All Others time, which could be caused by the execution of some Python code in your program."

**Comment by zaccharieramzi** [comment]
Hmmm ok, I still think that in this case being very emphatic about the "NOT input-bound" is a bit misleading but I get your point. Closing this.
