### ISSUE TITLE
How to generate 'A ProfileProto binary proto file' for profile_path ?(in tensorflow 2.2)

### ISSUE THREAD

**Issue by gyshi** [tensorflow/profiler#20]
USe tf2.2 cpu,  the profiler only have `tf.profiler.experimental.Profile` to generate files for tensorborad，

but i want to generate A ProfileProto binary proto file， their don't have ProfileContext，could you help me

**Comment by qiuminxu** [comment]
It would be helpful if you can describe your question more clearly. TF 2 profiler doesn't use ProfileContext or ProfileProto.

**Comment by gyshi** [comment]
thx, i have resolved it, i use chrome//tracing to get the result what i want.
