### ISSUE TITLE
DUMMY operations, confusing

### ISSUE THREAD

**Issue by fostiropoulos** [tensorflow/profiler#249]
I am using torch-xla-nightly (although the same issue exists for 1.7) and following the multiprocessing tutorial structure provided by the [documentation](https://pytorch.org/xla/release/1.7/index.html#running-on-multiple-xla-devices-with-multiprocessing). I use tensorflow 2.4 and tensorboard 2.3

Some operations are confusing as to what they mean. Example:

![image](https://user-images.githubusercontent.com/4337024/102527511-0d537000-4052-11eb-934d-7b1ed403ddc1.png)

Specifically the dummy operations `DUMMY_BEFORE_HLO_PASSES` , they seem to be related to some internal process that I couldn't find documented anywhere.

**Comment by qiuminxu** [comment]
The new behavior is related to this PR:
https://github.com/tensorflow/tensorflow/commit/9dc5df5f0f2bc1b75e4672b317a826b8d780e10c

**Comment by fostiropoulos** [comment]
@qiuminxu I haven't been able to verify, is this resolved by the PR?
