### ISSUE TITLE
tf.data_bottleneck_analyzer screen fails to load

### ISSUE THREAD

**Issue by rafwaf** [tensorflow/profiler#251]
Hi,
For some reason the tf.data_botteleneck_analyzer tool/screen fails to load. It just hangs indefinitely on the loading screen.

It might be relevant to note that the overview screen says that my program is NOT input bound and waits for new data for 0.0 ms. I wonder if this might be an edge case that confuses the bottleneck analyzer as there is no bottlenec?

This happens with the pod viewer as well, however, I am more interested in the tf.data bottleneck analyzer. All of the other 6 tools work fine (total of 8 tools).

I am using one host and one GPU.

tensorboard                            2.4.0
tensorboard-plugin-profile    2.4.0
tensorboard-plugin-wit         1.7.0
tensorboardX                         2.1
tensorflow                              2.3.1
tensorflow-addons                 0.11.2
tensorflow-estimator              2.3.0
tensorflow-gpu                      2.3.1

Please let me know what other info you might need (ideally with a quick pointer or link as to how to attain it).

Thank you very much for your time.

**Comment by ckluk** [comment]
Hi,

The tools shouldn't hang even if there is no bottleneck.
If possible, can you please send us your entire profile log directory so
that we can try to reproduce?
Thanks,
-ck

**Comment by rafwaf** [comment]
Happy to attach it but... how do I attach a file? Also, I'm assuming a zipped folder would be good? 
Thanks.

**Comment by ckluk** [comment]
Yes, a zipped folder would be good. You can directly send it to me:
ckluk@google.com
thanks

**Comment by rafwaf** [comment]
OK. I'll email. Sorry it took long.
Thanks

**Comment by randolfo75** [comment]
Exactly same problem here.

**Comment by ckluk** [comment]
FYI, I have got a reproducer from rafwaf and filed a bug. It will be
handled by its owner after the new year.

**Comment by jray319** [comment]
I wasn't able to reproduce the issue in colab. I uploaded @rafwaf's trace to colab and opened it in TensorBoard.

![image](https://user-images.githubusercontent.com/5633883/112219579-6c40fc00-8be2-11eb-90c5-694ae69aaa12.png)

Could you try again to see if the issue still persists? Perhaps you need to use TensorFlow 2.4.1.

**Comment by rafwaf** [comment]
Thank you, @jray319. using 2.4.1 does solve the problem
