### ISSUE TITLE
What's Happening During Self Time

### ISSUE THREAD

**Issue by yuqil725** [tensorflow/profiler#278]
Hi teams,
Really appreciate this lib helping us dive into the computing tracing time during the training process. However, we had a hard time understanding what's happening during the self-time period (e.g. the self-time of “GPU train 30” shown as below).
![image](https://user-images.githubusercontent.com/76530451/109915382-bd16a200-7c7f-11eb-94a6-2a73a9fefa6f.png)
In other words, during a step, what's happening when tf.profiler didn't show anything?
Following the above question, what factor should I consider to reduce the self-time period?
It is very surprising that the sum of the lower level's operation doesn't even make up 70% of the step time.

**Comment by yisitu** [comment]
Hi, a lot more information is needed for further analysis. Would it be possible to upload the *.xplane.pb profile, or provide a reproducible?

> In other words, during a step, what's happening when tf.profiler didn't show anything?

Could you elaborate on what is missing, where? i.e. where one might expect the tf.profiler to show something, but doesn't? Do you mean that the red rectangle boxes should have traces?

> Following the above question, what factor should I consider to reduce the self-time period?

Without the details, I can only provide some general pointers. Find the main bottleneck in this period. Start with a higher level questions: is this limited by host or GPU? If GPU bound, is the GPU is being used efficiently. The second part requires a deeper analysis. 

The [Overview Page](https://www.tensorflow.org/guide/profiler#overview_page) has some high level recommendations, do see if these are actionable. In addition, the [GPU Performance Optimization Guide](https://www.tensorflow.org/guide/gpu_performance_analysis) will also be very helpful here.

**Comment by yuqil725** [comment]
Thanks for the response. For sure, here is my *.xplane.pb file, which is obtained by training a single-hidden-layer feedforward neural network. 
[d7c18c882de2.xplane.pb.zip](https://github.com/tensorflow/profiler/files/6152572/d7c18c882de2.xplane.pb.zip)
My team is working on a project to understand what's exactly happening when a DNN was training from the highest level (python level) to the lowest level (GPU level). Therefore, a deeper understanding of the profiler would be very helpful.
> Could you elaborate on what is missing, where? i.e. where one might expect the tf.profiler to show something, but doesn't? Do you mean that the red rectangle boxes should have traces?

Yes, I expected the red rectangle boxes should have some traces.
![Screen Shot 2021-03-16 at 6 43 56 PM](https://user-images.githubusercontent.com/76530451/111389637-b0cf1380-8687-11eb-9fdd-5dfc1b4b5252.png)

Let's first confirm your definition of self-time: let's say the first row with **train 30** was called operation 1. Under operation 1, there are a bunch of lower-level operations composed **train 30** I called them operation 1.1. Self time is the period where the total period of operation 1 - the total period of operation 1.1. In the other words, the gaps between the higher and lower operations (the red rectangular I marked). 

If now we are on the same understanding of the self time definition, let's come back to my question. Why the higher-level operations were not fully filled by the lower-level operations. I could not elaborate on what's missing because this is something I would like to know.

My intuition was: train 30 was one step during training, this operation **"train 30"** may be fully filled by lower operations such as CPU GPU communication time, dense layer computing time, backward propagation time. However, the fact from profiler was that **train 30** was not fully filled by those lower-level operations but had some empty period, the self time. Therefore, this is more like a general question: what's happening during the self time? Is there any methodology to help us understand why self time exist?

**Comment by yisitu** [comment]
Our understanding of self time is consistent. Have you checked out the [pod viewer](https://www.tensorflow.org/guide/profiler#pod_viewer) in the profiler? It looks like Step 30 is bottlenecked on "Kernel Launch" and secondary reason is "All others, including Python overhead".

You could try to increase the trace level of Python tracer to see if that gives more trace events for Python in the red rectangle. For kernel launch overheads, the profiler does not emit events.

Beyond that, the profiler is working as intended as this is not a bug. Also do check out the guides from my earlier comment.

**Comment by yuqil725** [comment]
Thank you for the instant response! Just the last question: how to increase the trace level? Is there an argument in tf.profile to set the trace level (e.g. I just made up one example: tf.profiler.experiment.trace(level = "high"))?

**Comment by yisitu** [comment]
It is this API instead: https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/client/trace
Which takes in a ["ProfilerOptions"](https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/ProfilerOptions) which has a setting for python_tracer_level.

If you use the TensorBoard [Capture Profile](https://www.tensorflow.org/guide/profiler#capture_dialog) dialog, there is a drop down on the dialog to set the Python Trace Level.
