### ISSUE TITLE
Increasing granularity of trace

### ISSUE THREAD

**Issue by mossjacob** [tensorflow/profiler#29]
![trace](https://user-images.githubusercontent.com/3687111/83066964-c40fe480-a05d-11ea-91ae-ce5265955ea4.PNG)
![trace1](https://user-images.githubusercontent.com/3687111/83067760-21f0fc00-a05f-11ea-9619-7c7181878ebb.PNG)

Here I have part of the trace of my model which contains some custom MCMC samplers along with a No U-Turn Sampler from TFP. I'm trying to diagnose why running on the GPU is taking so much longer than on the CPU. I'm wondering if there's a way of getting more precise information about what is being processed. In the image the longest blocks don't give any information about what's specifically going that makes them take so long. 

Here is the full log: [20200527-152907.zip](https://github.com/tensorflow/profiler/files/4691555/20200527-152907.zip)

Furthermore when I run the same code just on the CPU, the trace no longer shows the mcmc_sample_chain blocks:
![trace2](https://user-images.githubusercontent.com/3687111/83067647-f40bb780-a05e-11ea-8f53-d33979687594.PNG)

Why is there such a big difference between the GPU and CPU trace? Can I get more specific information for the GPU trace?

**Comment by ckluk** [comment]
Hi,
I look at your profile log. From the Overview Page result (see below), ~86%
of your step time is spent on the "Kernel Launch" and ~8% is spent on "All
Other" time.
This probably means that the Ops that you execute on GPU are too tiny so
that the overhead of launching them dominates. Perhaps, you need to
increase the execution granularity on the GPU by "fusing" multiple kernels
together.
Hope this helps,
-ck

[image: image.png]

**Comment by JCobbles** [comment]
Thanks @ckluk , but is there a way to see more information for the blocks after around 25 seconds? Because beyond that point the trace doesn't give any information about what's going on

**Comment by ckluk** [comment]
The long spans that you see after 25 secs are simply scopes of a bunch of
related activities. Usually you will see the individual activities spreaded
over many threads (i.e. rows on the trace viewer).

**Comment by ydennisy** [comment]
@ckluk how does one "fuse" multiple kernels together? Especially when using something like keras?
