### ISSUE TITLE
The pluggin  disappeared in tensorboard once I install it

### ISSUE THREAD

**Issue by yiliu9090** [tensorflow/profiler#301]
I am using Docker container nvcr.io/nvidia/tensorflow:21.03-tf2-py3
Once I install profile in the tensorboard `pip install -U tensorboard-plugin-profile`
The profile disappeared from the tensorboard all together. Please help!

**Comment by Jimicy** [comment]
This could be `tensorboard-plugin-profile` not matching with your tensorflow version?
The colab is a working example you can refer to: https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras
```
pip install -U tensorboard_plugin_profile
> Successfully installed gviz-api-1.9.0 tensorboard-plugin-profile-2.4.0
```
And the Tensorflow version used is
```
TensorFlow version:  2.2.0-dev20200405
```

But if you want the latest version of the profiler, it's recommended to install the nightly packages for
tensorflow, tensorboard, tensorboard profiler `tbp-nightly`
See: https://github.com/tensorflow/profiler/blob/master/install_and_run.py
```
pip3 install -U tf-nightly
pip3 install -U tb-nightly
pip3 install -U tbp-nightly
```
