### ISSUE TITLE
Export as CSV button on kernel stats doesn't work 

### ISSUE THREAD

**Issue by codeislife99** [tensorflow/profiler#335]
I tried the Quick Start Guide in the README.md and the Export as CSV option doesn't work. Inside GPU Multi-worker option, when I click it , it doesn't do anything. I am on a Mac OS. Even in the officially released versions this button doesn't work. Please look into this issue, as this blocks customers from doing further postprocessing on their kernel data. Thanks.

**Comment by codeislife99** [comment]
Ah I see the reason, the export as CSV button only works when there is a `..kernel_stats.pb` file. If there is only a single `..xplane.pb` file then the export as CSV button doesn't work. Is it possible to make it work for the latter as well ?

**Comment by cfRod** [comment]
Linking similar issue https://github.com/tensorflow/tensorboard/issues/6551#issuecomment-1696383179
