### ISSUE TITLE
large average time delay gap between profiling result and my print result

### ISSUE THREAD

**Issue by quxinqq** [tensorflow/profiler#349]
Problem:
model predict time delay is about 22-23ms each time  in printing way
model predict time delay is about 6ms each time in profile calculation way
Why so big gap between these two ways.

1.My Enviroment:
Linux version 3.10.0-957.27.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36)
tensorboard==2.2.2
tensorboard-plugin-profile==2.4.0
tensorflow==2.2.0
conda-build version : 3.15.1
python version : 3.7.6
cuda and cudnn version:
![图片](https://user-images.githubusercontent.com/88089887/127622245-e1187fb9-5732-4e4e-b4b3-66fd3e5bd5bd.png)
![图片](https://user-images.githubusercontent.com/88089887/127622549-692c5f2c-e6db-4e8f-a878-93c54a9adcaf.png)

2. time delay test code and print value:
import os
import tensorflow as tf
from datetime import datetime
import joblib
import json
import time
import numpy as np
from prb_allocation_v2 import calcaulate
from keras.models import load_model
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
tf.config.experimental.set_visible_devices(devices=gpus[0], device_type='GPU') 
tf.config.experimental.set_memory_growth(gpus[0], enable=True)
configs = json.load(open('../config_pipeline.json', 'r'))
HUBER_DELTA = configs['training']['HUBER_DELTA']
n_steps_forward = configs['data']['sequence_length'] 
tbs_model_path=configs['model_path']['tbs_model']
bler_model_path=configs['model_path']['bler_model']    
total_prbs=int(configs['data']['total_prbs'])
ue_low_threshold=np.array(configs['data']['ue_low_threshold'])
ue_high_threshold=np.array(configs['data']['ue_high_threshold'])
tbs_model=joblib.load(tbs_model_path)  
mcs_model_path='/home/xaqu/notebook_dir/SLA/saved_models/training_mcs_20210618-153954/model_best.h5'    
mcs_model = load_model(mcs_model_path)
test_x=np.loadtxt("test.csv", delimiter=",",skiprows=1)[0:,:-2]
n_features_mcs = int((test_x.shape[1]) / n_steps_forward)
test_x =test_x.reshape((test_x.shape[0], n_steps_forward, n_features_mcs)) 
for i in range(100):
    t_1=time.time()
    mcs_pred=mcs_model.predict(test_x,batch_size=10)
    print ('Numer %d time delay from data input to model predict result'%i,   (time.time()-t_1)*1000,'ms')
![图片](https://user-images.githubusercontent.com/88089887/127647646-9fed45a2-9ba2-4585-92e6-e4d7182c2fbc.png)

3. time delay test by profile calculation
import os
import tensorflow as tf
from datetime import datetime
import joblib
import json
import numpy as np
from prb_allocation_v2 import calcaulate
from keras.models import load_model
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
tf.config.experimental.set_visible_devices(devices=gpus[0], device_type='GPU') 
tf.config.experimental.set_memory_growth(gpus[0], enable=True)
configs = json.load(open('../config_pipeline.json', 'r'))
HUBER_DELTA = configs['training']['HUBER_DELTA']
n_steps_forward = configs['data']['sequence_length'] 
tbs_model_path=configs['model_path']['tbs_model']
bler_model_path=configs['model_path']['bler_model']    
total_prbs=int(configs['data']['total_prbs'])
ue_low_threshold=np.array(configs['data']['ue_low_threshold'])
ue_high_threshold=np.array(configs['data']['ue_high_threshold'])
tbs_model=joblib.load(tbs_model_path)  
mcs_model_path='/home/xaqu/notebook_dir/SLA/saved_models/training_mcs_20210618-153954/model_best.h5'    
mcs_model = load_model(mcs_model_path)
logs = os.path.join("/home/xaqu/notebook_dir/SLA/logs",datetime.now().strftime("%Y%m%d-%H%M%S"))
test_x_=np.loadtxt("test.csv", delimiter=",",skiprows=1)[0:,:-2]
n_features_mcs = int((test_x_.shape[1]) / n_steps_forward)
test_x_ =test_x_.reshape((test_x_.shape[0], n_steps_forward, n_features_mcs)) 
mcs_pred=mcs_model.predict(test_x_,batch_size=10)
with tf.profiler.experimental.Profile(logs): 
    for i in range(100):
        test_x=np.loadtxt("test.csv", delimiter=",",skiprows=1)[0:,:-2]
        n_features_mcs = int((test_x.shape[1]) / n_steps_forward)
        test_x =test_x.reshape((test_x.shape[0], n_steps_forward, n_features_mcs)) 
        mcs_pred=mcs_model.predict(test_x,batch_size=10)

![图片](https://user-images.githubusercontent.com/88089887/127647800-6ea92f44-4bf2-45e6-bd27-180c0e264780.png)

**Comment by quxinqq** [comment]
5.Added info about loaded_model structure:
![图片](https://user-images.githubusercontent.com/88089887/127626273-94488bf4-1c28-4c4c-b096-14543173cfa8.png)

**Comment by ckluk** [comment]
Is it possible for us to reproduce your issue?

**Comment by quxinqq** [comment]
@ckluk 
Can you please provide your mail address,  I'll send model file, test.csv and config.json and profile logs to you.Thanks.

**Comment by quxinqq** [comment]
I compressed related files and uploaded for your reference.
[model&input_csv&config_json.zip](https://github.com/tensorflow/profiler/files/6910484/model.input_csv.config_json.zip)
1.config_pipeline load place,please change to your path for "config_pipeline.json"
configs = json.load(open('../config_pipeline.json', 'r'))

2.model path, please change  to your path for "model_best.h5"
mcs_model_path='/home/xaqu/notebook_dir/SLA/saved_models/training_mcs_20210618-153954/model_best.h5'

3.input csv path, please change to your path for "test.csv"
test_x=np.loadtxt("test.csv", delimiter=",",skiprows=1)[0:,:-2]

4.please delete or uncomment below sentence in code because I didn't upload tbs_model file.
tbs_model=joblib.load(tbs_model_path)

Then, you can run in your enviroment.

**Comment by quxinqq** [comment]
Is there any update? thanks so much for your update.

**Comment by trisolaran** [comment]
Maybe we had different definition of steps.
Can you show us the trace viewer's snapshot.
can you wrap your step with traceme defined in 
from tensorflow.python.profiler.traceme import TraceMe

 with traceme.TraceMe("my step"):
    # do your step.

you can also enable python tracer.

**Comment by trisolaran** [comment]
nvm, I was able to load your trace. let me know if you can not see the following snapshots.
https://screenshot.googleplex.com/AnUAzzZLXXWYLKd.png

**Comment by quxinqq** [comment]
I can't open https://screenshot.googleplex.com/AnUAzzZLXXWYLKd.png due to log in issue.

**Comment by quxinqq** [comment]
> 
> 
> nvm, I was able to load your trace. let me know if you can not see the following snapshots.
> https://screenshot.googleplex.com/AnUAzzZLXXWYLKd.png

I can't open https://screenshot.googleplex.com/AnUAzzZLXXWYLKd.png due to log in issue.

**Comment by trisolaran** [comment]
![explain](https://user-images.githubusercontent.com/33339844/128382253-5c3271ba-1d8d-4702-82ee-cf4dbf9c555f.png)

**Comment by trisolaran** [comment]
one obvious abnormal thing is that you had too many gpu streams, normally a tf session or tf2 only use 3-5 streams.
but I don't know what causing it.

**Comment by quxinqq** [comment]
> 
> 
> Maybe we had different definition of steps.
> Can you show us the trace viewer's snapshot.
> can you wrap your step with traceme defined in
> from tensorflow.python.profiler.traceme import TraceMe
> 
> with traceme.TraceMe("my step"):
> # do your step.
> 
> you can also enable python tracer.

1. Below is new trace log after adding Traceme in my test python log
import os
import tensorflow as tf
from datetime import datetime
import joblib
import json
import numpy as np
from prb_allocation_v2 import calcaulate
from keras.models import load_model
from tensorflow.python.profiler.traceme import TraceMe
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
tf.config.experimental.set_visible_devices(devices=gpus[0], device_type='GPU') 
tf.config.experimental.set_memory_growth(gpus[0], enable=True)
configs = json.load(open('../config_pipeline.json', 'r'))
n_steps_forward = 10 
mcs_model_path='/home/xaqu/notebook_dir/SLA/saved_models/training_mcs_20210618-153954/model_best.h5'    
mcs_model = load_model(mcs_model_path)
logs = os.path.join("/home/xaqu/notebook_dir/SLA/logs",datetime.now().strftime("%Y%m%d-%H%M%S"))
test_x_=np.loadtxt("test.csv", delimiter=",",skiprows=1)[0:,:-2]
n_features_mcs = int((test_x_.shape[1]) / n_steps_forward)
test_x_ =test_x_.reshape((test_x_.shape[0], n_steps_forward, n_features_mcs)) 
mcs_pred=mcs_model.predict(test_x_)
with tf.profiler.experimental.Profile(logs): 
    for i in range(100):
        with TraceMe("my step"):
            mcs_pred=mcs_model.predict(test_x_)

2.Trace ovevie graph
 **Totally 100 steps runned in my log and the grah still showed average ~6ms latency per step.**
![图片](https://user-images.githubusercontent.com/88089887/128487097-01459835-2866-4954-afb0-3b13db46d798.png)

3. Profile Trace log zip file
[20210806-170130.zip](https://github.com/tensorflow/profiler/files/6944474/20210806-170130.zip)


4.Trace viewer Snapshot
**From below graph, I found tensorflow operations were executed since 24ms (start from 0ms) and ended with about 30ms.
Why nothing to do between 0ms~24ms duration, is it python issue? or any other issue?**
![图片](https://user-images.githubusercontent.com/88089887/128488423-277188fd-98dd-463f-8ada-402ba96b9dd3.png)

**Comment by quxinqq** [comment]
![图片](https://user-images.githubusercontent.com/88089887/128489322-440f02b1-9896-4b47-983b-c8c093ac8f4d.png)
