### ISSUE TITLE
Tracing Operations Only

### ISSUE THREAD

**Issue by NoraAl** [tensorflow/profiler#360]
Hi there,

I am using `tf.profiler.experimental.Trace` to compare the performance of a new operation to an existing one. However, **kernel launch** is taking very long and affecting the result. 
I tried to make everything deterministic in each run, meaning the same data with no shuffling, same model with the same weights and no dropouts, same everything. However, the same operation, say **_mul_**, takes different amounts of time in each identical run, although it has the same number of occurrences.

I tried two different AWS instances, kernel launch became less significant. Still, the same operation with the same number of occurrences takes different amounts of time. 

What am I missing?

Thanks

**Comment by Matt-Hurd** [comment]
As this issue hasn't been touched in some time, I'm closing it out. Please update this thread if it is still occurring and is reproducible, and I will reopen it.
