### ISSUE TITLE
Where can I ask questions about not obvious tf ops?

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/profiler#4]
When looking at the tensorflow stats, some ops are quite straight forward to understand, like `Conv2DBackpropFilter`. However, some others, like `_Recv` are not necessarily obvious (at least to me).

I figured it would be inefficient for you to have in GitHub issues both questions about understanding the profiler (and the tf ops in particular) and real issues (doc, bugs, features), so I wondered where was the best place I could ask these questions (because I also thought SO was not exactly the right place).

**Comment by ckluk** [comment]
Perhaps, ask your question in:
https://groups.google.com/a/tensorflow.org/g/discuss

**Comment by zaccharieramzi** [comment]
I had a 404 with your link, but I guess you meant: https://groups.google.com/a/tensorflow.org/forum/#!forum/discuss .

Closing this, thanks!
