### ISSUE TITLE
TPU VM + Pytorch/XLA profiling shows zero device compute

### ISSUE THREAD

**Issue by coleridge72** [tensorflow/profiler#400]
I've been using the profiler on a TPU VM with Pytorch following this [guide](https://cloud.google.com/tpu/docs/pytorch-xla-performance-profiling-tpu-vm#tpu-vm) 

The overview page shows zero "device compute" in the graph and summary. I notice this is actually also the case in the screenshot of the guide. The trace viewer *does* show activity happening on the cores though.

Could this be a bug? or maybe I am just missing something.

Thanks

Specs:
```
torch==1.10.0
torch-xla==1.10
torchvision==0.11.1
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-profile==2.5.0
tensorboard-plugin-wit==1.8.0
```

![Screenshot 2022-03-22 at 20 04 42](https://user-images.githubusercontent.com/35977965/159566404-87d5b8af-edee-4cbb-a788-95502c33f818.png)

**Comment by Matt-Hurd** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
