### ISSUE TITLE
Tensorflow operations order in tensorflow stats view

### ISSUE THREAD

**Issue by Gforky** [tensorflow/profiler#402]
Hey guys, I have a novice question about profiler.
In tensorflow stats view, what is the default order of operations in "Tensorflow Operations"?
![image](https://user-images.githubusercontent.com/4157614/160102374-736fc78e-3b10-4411-9c24-f34b82734739.png)

**Comment by zzzaries** [comment]
it is sorted by default by how time consuming the operation is (Total time)

**Comment by Gforky** [comment]
> it is sorted by default by how time consuming the operation is (Total time)

Yeah, I see, it's a dummy question, thanks for the reply.
