### ISSUE TITLE
Failed to load libcupti (is it installed and accessible?)

### ISSUE THREAD

**Issue by nlpming** [tensorflow/profiler#443]
verion:
- tensorflow 2.3
- cuda 10.1
- tensorboard-plugin-profile 2.3.0
- tensorboard 2.3
- NVIDIA Driver Version: 418.126.02

I'm pretty sure libcupti.so.10.1 is exist in path  /usr/local/cuda/extras/CUPTI/lib64
and I append /usr/local/cuda/extras/CUPTI/lib64 to LD_LIBRARY_PATH,
but i get error "Failed to load libcupti (is it installed and accessible?)"

export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

How can I solve this problem?

**Comment by toshiyukinakata** [comment]
In a newer version of Tensorflow,
I had to manually create a symbolic link as below because
libcupti.so.11.2 seems to be explicitly specified, which is a mistake I believe..
libcupti.so.11.2 -> libcupti.so.2022.2.1
in /usr/local/cuda/extras/CUPTI/lib64
