### ISSUE TITLE
Errors when serving tensorboard from subdirectory

### ISSUE THREAD

**Issue by yegortokmakov** [tensorflow/profiler#45]
In my case tensorboard is served in a subdirectory: `http://hostname/tensorboard/`. Profile plugin fails to load bundle.js:
`GET https://hostname/data/plugin/profile/bundle.js net::ERR_ABORTED 404 (Not Found)`
showuld be `https://hostname/tensorboard/data/plugin/profile/bundle.js`.

When fixing base url of the plugin index html, new error comes from bundle.js:
`GET https://hostname/tensorboard/data/plugin/profile/tools 404 (Not Found)`

Is it something that can be fixed easily? Or is it Tensorboards plugin system and not the Profiler plugin itself?

**Comment by yegortokmakov** [comment]
I guess it's iframe's base url and API_PREFIX in https://github.com/tensorflow/profiler/blob/master/frontend/app/common/constants/constants.ts#L8

**Comment by ydko** [comment]
It has been modified to support sub directories.
https://github.com/tensorflow/profiler/commit/4182381cfd57a6696bc4e71cbb7580e2cb6643e2

**Comment by yegortokmakov** [comment]
@ydko, awesome, thanks! 

I just understood `tensorboard-plugin-profile` [package](https://pypi.org/project/tensorboard-plugin-profile/#history) is not built from this repo, but from `tensorboard`. `install_and_run.py` is using the version 2.2.0 from pypi and not the latest code.

How do I test the latest changes in this plugin? And what are your plans on packaging the code in this repo?

**Comment by ydko** [comment]
[The nightly package](https://pypi.org/project/tbp-nightly/#history) is built every day.  You can test it with the nightly version.

pip install tbp-nightly

**Comment by yegortokmakov** [comment]
it works! thanks a lot @ydko
