### ISSUE TITLE
Profiler : No Profile Data was Found in Collab code example

### ISSUE THREAD

**Issue by JaShams** [tensorflow/profiler#602]
I am new to Tensorflow, and was trying to figure out how to use the profiler. By following the docs ( https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras ), I got tensorboard working on my remote development machine and could view everything except the profiler output.  
I then tried executing the code example mentioned in the doc in Collab ( https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb ) only to see the same output. 

Is the code example not up to date or is there an issue somewhere else?

Thanks
![Screenshot 2023-04-15 000305](https://user-images.githubusercontent.com/54030413/232128138-6e3dcd4b-b3ef-43f1-8ddf-0c43653eb695.jpg)

**Comment by rick020** [comment]
I am running into the same problem after running the command `tensorboard --logdir logs/`
System information:
- Azure ML compute instance
- Linux 22.08.19

Environment information
- python=3.8.16
- pip= 22.3.1
- tensorboard=2.10.1
- tensorboard-plugin-profile=2.10.1


Files in logs directory
<img width="1053" alt="files" src="https://user-images.githubusercontent.com/19412391/232771173-87a3dfb3-a465-4651-8f3c-6f2735ed7d60.png">

Tensorboard:
<img width="1501" alt="tb" src="https://user-images.githubusercontent.com/19412391/232771778-5cbb403e-81eb-4c64-8d77-5266f218b492.png">

**Comment by gxxxh** [comment]
I run into the same problem, too

**Comment by Pondiniii** [comment]
I can confirm that I'm experiencing the same issue 🫤

**Comment by caleb1010** [comment]
same here. Does anybody know how to solve this? Several months have passed, without even a single reply from the developers.

**Comment by zzzaries** [comment]
Hey, just took a look, seems the log directory is missing a events file, we will look into fix this.
As a quick workaround for now, please try:
1. download the events.out.tfevents file at
 https://github.com/tensorflow/profiler/tree/master/demo
2. upload this file to the demo log directory like: 
<img width="392" alt="Screenshot 2023-09-05 at 9 49 44 PM" src="https://github.com/tensorflow/profiler/assets/12827972/5ea02364-5162-4b8d-a204-bdb79046923e">

then you should be able to see the profiler:
<img width="1766" alt="Screenshot 2023-09-05 at 9 46 13 PM" src="https://github.com/tensorflow/profiler/assets/12827972/311392a2-9d4d-45b1-9cca-a9921bd3adeb">

**Comment by lakeyk** [comment]
When using the profiler, the logs address should include the run ID.
In the original example, this would be: %tensorboard --logdir='logs/20230414-182044'

**Comment by ZM-J** [comment]
> Hey, just took a look, seems the log directory is missing an events file, we will look into fixing this. As a quick workaround for now, please try:
> 
> 1. download the events.out.tfevents file at
>    https://github.com/tensorflow/profiler/tree/master/demo
> 2. upload this file to the demo log directory like:
> 
> <img alt="Screenshot 2023-09-05 at 9 49 44 PM" width="392" src="https://private-user-images.githubusercontent.com/12827972/265896306-5ea02364-5162-4b8d-a204-bdb79046923e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzUzMzYsIm5iZiI6MTcxMzMzNTAzNiwicGF0aCI6Ii8xMjgyNzk3Mi8yNjU4OTYzMDYtNWVhMDIzNjQtNTE2Mi00YjhkLWEyMDQtYmRiNzkwNDY5MjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA2MjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMTU3NzQ3M2ZjYmNhOTZmMjBiOWVhNGVhNDcxYTZhMzY3MTc2ZWM1MTFmNDA1ZWZlZTczN2MxZWZhMTQzMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PXDxbjjk7WbLQaoxpbRNcjaObU_ZqaNkGluU7NF8JDo">
> then you should be able to see the profiler: <img alt="Screenshot 2023-09-05 at 9 46 13 PM" width="1766" src="https://private-user-images.githubusercontent.com/12827972/265896472-311392a2-9d4d-45b1-9cca-a9921bd3adeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzUzMzYsIm5iZiI6MTcxMzMzNTAzNiwicGF0aCI6Ii8xMjgyNzk3Mi8yNjU4OTY0NzItMzExMzkyYTItOWQ0ZC00NWIxLTljY2EtYTk5MjFiZDNhZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA2MjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZGUwMmU0N2Y2YjBmYjkwZTAxOTExZGI0YmExMGMyNDJlNDk4MTk5OTNmYTQ3YmZhN2RhOGJlMTMyNDJjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNRgY1cBDWPCRtAOgcrVfHDXc-dRRgKS0c19lUb_P-c">

Hi, I have the same problem showing that "No profile data was found". However, there exists a file `events.out.tfevents.1713334799.XX.profile-empty` in folder `logs/20240417-141935`.

My TF version is also `2.10.1`, but I try to profile everything in my own computer.

I even tried the advice from @lakeyk , but that still didn't work.

Seems that everything required by tensorboard is present:

```
│  events.out.tfevents.1713334799.XX.profile-empty
│
├─plugins
│  └─profile
│      └─2024_04_17_06_19_59
│              XX.input_pipeline.pb
│              XX.kernel_stats.pb
│              XX.memory_profile.json.gz
│              XX.overview_page.pb
│              XX.tensorflow_stats.pb
│              XX.trace.json.gz
│              XX.xplane.pb
│
├─train
│      events.out.tfevents.1713334775.XX.40004.0.v2
│
└─validation
        events.out.tfevents.1713334787.XX.40004.1.v2
```

I'm not sure whether it is an issue of this version of TF or not though.

**Comment by ghsanti** [comment]
@lakeyk could you share a gist/colab notebook to reproduce it?
