### ISSUE TITLE
Google colab demo broken

### ISSUE THREAD

**Issue by asynap** [tensorflow/profiler#653]
The demo colab linked in the readme is broken.

Collab: https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb

Readme Link: https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

![image](https://github.com/tensorflow/profiler/assets/138231968/8df18f86-f46c-4d9d-959c-ef4a9b856f5c)

Related: https://github.com/tensorflow/tensorflow/issues/61212

**Comment by zzzaries** [comment]
see https://github.com/tensorflow/profiler/issues/602#issuecomment-1707656079
