### ISSUE TITLE
No profile directory generated under logs.

### ISSUE THREAD

**Issue by PurvangL** [tensorflow/profiler#741]
I am trying to train on my **H100** and trying to capture profile but there is no profile folder generated. 
code block
```
callbacks.append(tf.keras.callbacks.TensorBoard(log_dir="checkpoints/logs", histogram_freq=1, profile_batch=(0, 100)))
```

packages.
tf-nightly                    2.14.0.dev20230706
tensorboard                   2.14.0
tensorboard-plugin-profile    2.14.0

Please let me know if any additional information needed.

**Comment by Matt-Hurd** [comment]
Closing this issue as it is stale. If you are still running into this issue, please provide fresh information and we'll reopen this.
