### ISSUE TITLE
Question: Can we measure CPU/GPU performance of only inference using this profiler?

### ISSUE THREAD

**Issue by y-vectorfield** [tensorflow/profiler#753]
I want to measure CPU/GPU performance of only inference. (I don't want to do that of training.) In addition, I want to analyze measurement results using TensorBoard. Can I measure it using this profiler? If we can do that, please let me know how to use it. I read this tool's document and tutorial; however, I could not measure it yet.

**Comment by Matt-Hurd** [comment]
With JAX, inference measurement and analysis is straight-foward. [TraceAnnotations](https://jax.readthedocs.io/en/latest/_autosummary/jax.profiler.TraceAnnotation.html) can be used to denote a single inference batch, which the profiler should automatically detect as inference based on the HLO ops used.

I believe the same functionality should be present for Tensorflow, however I'm not familiar with the instrumentation.
