### ISSUE TITLE
Profiler data is not correct 

### ISSUE THREAD

**Issue by akote123** [tensorflow/profiler#784]
Hello  ,
I wanted to use tensorboard for inference,
tf.profiler.experimental.start('logs')
output = model.predict(encoded_input, verbose=False)[0]
tf.profiler.experimental.stop()
I have tried this way . 
I am not getting op level details of the ,model inference
The profiler snippet is 
<img width="960" alt="profiler" src="https://github.com/tensorflow/profiler/assets/133775732/11edb2ad-adee-4e5c-9d1d-f6727374a362">

 May I know how we can get profiler op level data for model inference
Reference Issue :https://github.com/tensorflow/tensorflow/issues/62373

**Comment by Matt-Hurd** [comment]
For inference, you may need to specifically add step markers to your code. During training, we're able to guess some of the patterns for each step. Sadly this is not the case for inference.

Closing out this issue as it's stale. If this is still and issue, please reopen it and provide some more recent information.
