### ISSUE TITLE
step time breakdown question

### ISSUE THREAD

**Issue by nbcsm** [tensorflow/profiler#83]
In tensorboard, per step time breakdown is displayed.
![image](https://user-images.githubusercontent.com/32868157/85950079-1578ff80-b98d-11ea-94cf-117c1333078e.png)

If I understand correctly, core TF side runs a profiler to capture all kinds of events, e.g. kernel starts/ends, memory H2D, D2H etc.
But given an event, how TF knows which step this event belongs to? Or how TF knows when a step begins/ends?
Tried to dig into TF profiler code, but didn't find a clue...

any comments please?
thanks.

**Comment by ckluk** [comment]
We added step-tracking code to some frameworks such as Keras.
In the upcoming TF 2.3 release, users can also add this step-tracking code
to their own frameworks.

**Comment by nbcsm** [comment]
thanks for the information, @ckluk.

could you help to point out where I can find the "step-tracking" logic please?
really appreciate.
