### ISSUE TITLE
Profiler plugin does not search subdirectories the same as Tensorboard

### ISSUE THREAD

**Issue by thenhz** [tensorflow/profiler#835]
I'm trying to profile my application to find out any bottleneck but I wasn't able to see any proifile tab in tensorboard. I then tryied to run the tensorboard profiling example available at [https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb](url) but I dicovered that even there is not working. I'm using the NCG official images through docker but if you would like to replicate the problem is enopugh to run the colab notebook at the link I've provided above.

**Comment by stellarpower** [comment]
Is there a reason profiling support has been dropped? Or is it expected to be functional still? 

I see a mention in the docs for the Tensorboard ctor [here](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#args) that it may be:
> profile_batch 	(Not supported at this time) ...

but there is no accompanying explanation as to why it's currently unsupported, or the extent of this. I don't see this string or a deprecation warning anywhere on github within the tensorflow organisation, as I assume the docs are auto-generated.

Has it been disabled in the current version? It seems a bit of an issue if the docs on profiling are non-functional and there's no mention if there is a reason it's currently been de-activated.

**Comment by conormelody** [comment]
Also having this issue, in the colab notebook example and elsewhere.

@stellarpower is onto something, as the version of tensorflow used when I ran the colab notebook is 2.15.0, and no Profile data widget is displayed.

![Screenshot 2024-06-06 at 16 43 42](https://github.com/tensorflow/profiler/assets/90448601/43ff1298-32c5-402f-ab53-9371e95406e3)

![Screenshot 2024-06-06 at 16 44 09](https://github.com/tensorflow/profiler/assets/90448601/2731624e-4d4a-4818-a6d9-7d5665522ba3)

Could anyone confirm if Profiling has been disabled?

**Comment by agniszczotka** [comment]
I have same problem with using profiler both colab and my local machine, I am also looking for solution.

**Comment by Matt-Hurd** [comment]
I'd like to use this issue to consolidate a number of issues from the main tensorflow repo.

https://github.com/tensorflow/tensorflow/issues/61212
https://github.com/tensorflow/tensorflow/issues/62373

**Comment by Matt-Hurd** [comment]
This is resolved in tbp-nightly as of 2024-12-20, and will be included in the next release.
