### ISSUE TITLE
Profiling integer dtype ops

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/profiler#85]
I would be interested in profiling ops that act on integer tensors on GPU.

For example I would like to profile the addition in the following fashion (see [this colab with tboard](https://colab.research.google.com/drive/1uuvPs68dObcQ0HyAocbjr7MJHxqhnwdW?usp=sharing)):

```python
import tensorflow as tf
chosen_dtype = tf.int32
a = tf.constant([7] * 100000, dtype=chosen_dtype)

with tf.profiler.experimental.Profile("logs"):
  for i in range(1):
    a + 3
```

However, doing this the profiler doesn't record any GPU operation. If I just change the `chosen_dtype` to `tf.float32`, then I have the correct GPU operations (in addition to the eager execution operations).

How can I profile integer dtype ops?

**Comment by ckluk** [comment]
It doesn't seem to be a profiler issue. Apparently, when integer is used,
the ops are scheduled on the CPU instead of GPU (you should see those CPU
ops in the profile).
So, you probably need to ask this question in the general TF forum for how
to force those integer ops to run on the GPU.

**Comment by zaccharieramzi** [comment]
You are right
