### ISSUE TITLE
Memory use profiling docs

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/profiler#86]
From what I understand in [this tweet](https://twitter.com/TensorFlow/status/1278404941275512833?s=20) by the official TensorFlow account, it seems that in tf 2.3, the profiler will feature a memory tab.

However, when using it (I can provide a colab if needed), I didn't see it in tensorboard.

I guess it's a matter of correctly using the ProfileOptions, but I don't know how, could you give some insights in the docs?

**Comment by ckluk** [comment]
The memory profiler located in the same place as other profiling tools
(i.e. Overview Page, Trace Viewer). So, you should see 6 tools altogether.
It does not require special ProfileOptions to trigger it.

**Comment by zaccharieramzi** [comment]
Indeed. It just recently appeared for me, but it is here now. Thanks!
